### ISSUE TITLE
Gene Ontology for mouse not working

### ISSUE THREAD

**Issue by akhileshmishra0908** [dbdimitrov/BingleSeq#9]
Hi,

I want to use BingleSeq for RNASeq data analysis on Mouse genome but it continuously throwing the same error of “Incorrect Gene Type” (Please find the attachment). I tried all the possibility but I am not able to resolve it.

Further, in gene Ontology section, there are two time mm9 genome is mentioned in the “Select Genome” section. What is the explanation behind it? 

I am attaching a sample and meta data file for your reference. Your response will be highly appreciated.

[design_BingleSeq.txt](https://github.com/dbdimitrov/BingleSeq/files/6744087/design_BingleSeq.txt)
![Image](https://user-images.githubusercontent.com/70369559/124033436-8d726f00-d9bf-11eb-9e70-5328dcbec283.PNG)
[Sample_Data.txt](https://github.com/dbdimitrov/BingleSeq/files/6744088/Sample_Data.txt)

Thanks & Best Regards,   

Akhilesh Mishra, Ph.D.

**Comment by dbdimitrov** [comment]
Dear Akhilesh Mishra,

Thank you for opening an issue.

I followed up on your example and noted a couple of things that might be the cause and appropriately updated BingleSeq.
So, I believe the issues should now be resolved and you should be able to obtain appropriate GO and footprint results for your data. However, I was unable to get meaningful results due to the small size of the sample data.

Please let me know if you notice any issues.

Regards,
Daniel
